In [1]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
import pandas as pd
import matplotlib.pyplot as plt

In [6]:
df=pd.read_csv('/content/Salary Data.csv')

In [7]:
df

    Experience Years  Salary
0                1.1   39343
1                1.2   42774
2                1.3   46205
3                1.5   37731
4                2.0   43525
5                2.2   39891
6                2.5   48266
7                2.9   56642
8                3.0   60150
9                3.2   54445
10               3.2   64445
11               3.5   60000
12               3.7   57189
13               3.8   60200
14               3.9   63218
15               4.0   55794
16               4.0   56957
17               4.1   57081
18               4.3   59095
19               4.5   61111
20               4.7   64500
21               4.9   67938
22               5.1   66029
23               5.3   83088
24               5.5   82200
25               5.9   81363
26               6.0   93940
27               6.2   91000
28               6.5   90000
29               6.8   91738
30               7.1   98273
31               7.9  101302
32               8.2  113812
33               8.5  111620
34               8.7  109431
35               9.0  105582
36               9.5  116969
37               9.6  112635
38              10.3  122391
39              10.5  121872

In [10]:
x=df[['YearsExperience']]
y=df[['Salary']]

KeyError: "None of [Index(['YearsExperience'], dtype='object')] are in the [columns]"

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=42) # Correct the order of variables assigned
reg = LinearRegression()
reg.fit(x_train, y_train)
predict = reg.predict(x_test)

In [ ]:
cd=float(input("enter your years of eperience: "))
input_data=pd.DataFrame([[cd]],columns=['YearsExperience'])
predicted_salary=reg.predict(input_data)

print(f"the predicted salary for {cd} years of exp is {predicted_salary[0][0]}")

In [ ]:
graph=plt.scatter(x_test,y_test,color='black')
plt.plot(x_test,predict,color='green')

In [ ]:
#kmeans clustering
import numpy as np
from sklearn.cluster import KMeans
data = np.array([
    [1, 2],
    [2, 3],
    [3, 2],
    [8, 7],
    [9, 8],
    [8, 9],
    [1, 4],
    [5, 9],
    [1, 9],
    [8, 7]
])

kmeans = KMeans(n_clusters=2)
kmeans.fit(data)
labels = kmeans.labels_
centroids = kmeans.cluster_centers_

plt.scatter(data[:, 0], data[:, 1], c=labels)
plt.scatter(centroids[:, 0], centroids[:, 1], c='red', marker='x')
plt.show()